/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the menu
         * @description The full validated menu: five categories, modifier groups, and every orderable drink with its customization allowance (FR-1).
         */
        get: operations["read_menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Newest first. Filter by status=active (placed plus in_progress) for the barista board, or by a single lifecycle status (FR-5).
         */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /**
         * Place an order
         * @description Validates every line against the live menu and assigns the daily order number (FR-3, FR-7). Broadcasts order:new.
         */
        post: operations["place_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one order
         * @description One order by id: the guest status view and the reconnect refetch (FR-4).
         */
        get: operations["read_order_api_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transition an order
         * @description Applies one legal transition (placed to in_progress, in_progress to completed, placed to completed, placed to cancelled) and broadcasts order:status (FR-5, FR-7).
         */
        patch: operations["update_status_api_orders__order_id__status_patch"];
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live order events (SSE)
         * @description Server-Sent Events stream: order:new on placement, order:status on every transition, and a heartbeat every 25 seconds while idle. Payloads are the camelCase event models from the schema.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description Error shape for 422 validation and transition rejections and
         *     404 unknown orders: a specific message plus per-line detail
         *     strings (FR-7).
         * @example {
         *       "details": [
         *         "item tan-cha is not on the menu"
         *       ],
         *       "error": "order line 1 is invalid"
         *     }
         */
        ApiError: {
            /**
             * Error
             * @description What went wrong, in one sentence.
             * @example order line 1 is invalid
             */
            error: string;
            /**
             * Details
             * @description Specific per-problem messages.
             * @example [
             *       "item tan-cha is not on the menu"
             *     ]
             */
            details: string[];
        };
        /**
         * Category
         * @description One of the five drink sections of the recipes menu.
         * @example {
         *       "id": "ca-phe",
         *       "name": "Coffee",
         *       "nameVi": "Cà Phê"
         *     }
         */
        Category: {
            /**
             * Id
             * @description Stable category slug, e.g. ca-phe.
             * @example ca-phe
             */
            id: string;
            /**
             * Namevi
             * @description Section heading as printed on the recipes menu.
             * @example Cà Phê
             */
            nameVi: string;
            /**
             * Name
             * @description English section label.
             * @example Coffee
             */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MenuDocument
         * @description The full validated menu served at GET /api/menu.
         * @example {
         *       "categories": [
         *         {
         *           "id": "ca-phe",
         *           "name": "Coffee",
         *           "nameVi": "Cà Phê"
         *         }
         *       ],
         *       "items": [
         *         {
         *           "categoryId": "mat-cha",
         *           "description": "Koicha whisked thick, your sweetener and milk of choice.",
         *           "id": "matcha-sua",
         *           "imagePath": null,
         *           "modifierGroupIds": [
         *             "milk-matcha-latte",
         *             "sweetener-matcha",
         *             "sweetness",
         *             "cold-foam"
         *           ],
         *           "name": "Matcha Latte",
         *           "nameVi": "Matcha Sữa",
         *           "temperatures": [
         *             "hot",
         *             "iced"
         *           ]
         *         }
         *       ],
         *       "modifierGroups": [
         *         {
         *           "defaultByTemperature": {
         *             "hot": "whole-milk",
         *             "iced": "oat-milk"
         *           },
         *           "dimension": "milk",
         *           "id": "milk-matcha-latte",
         *           "name": "Milk",
         *           "options": [
         *             {
         *               "id": "whole-milk",
         *               "name": "Whole milk",
         *               "temperatures": [
         *                 "hot"
         *               ]
         *             },
         *             {
         *               "id": "oat-milk",
         *               "name": "Oat milk",
         *               "temperatures": [
         *                 "hot",
         *                 "iced"
         *               ]
         *             }
         *           ],
         *           "required": true
         *         }
         *       ],
         *       "orderRules": {
         *         "maxQuantity": 10,
         *         "minQuantity": 1,
         *         "notesMaxLength": 200
         *       },
         *       "version": 1
         *     }
         */
        MenuDocument: {
            /**
             * Version
             * @description Menu document format version.
             * @example 1
             */
            version: number;
            /** @description Frozen per-line bounds. */
            orderRules: components["schemas"]["OrderRules"];
            /**
             * Categories
             * @description The five drink sections in display order.
             */
            categories: components["schemas"]["Category"][];
            /**
             * Modifiergroups
             * @description Shared customization groups referenced by items.
             */
            modifierGroups: components["schemas"]["ModifierGroup"][];
            /**
             * Items
             * @description Every orderable drink.
             */
            items: components["schemas"]["MenuItem"][];
        };
        /**
         * MenuItem
         * @description One orderable drink with its customization allowance.
         * @example {
         *       "categoryId": "mat-cha",
         *       "description": "Koicha whisked thick, your sweetener and milk of choice.",
         *       "id": "matcha-sua",
         *       "imagePath": null,
         *       "modifierGroupIds": [
         *         "milk-matcha-latte",
         *         "sweetener-matcha",
         *         "sweetness",
         *         "cold-foam"
         *       ],
         *       "name": "Matcha Latte",
         *       "nameVi": "Matcha Sữa",
         *       "temperatures": [
         *         "hot",
         *         "iced"
         *       ]
         *     }
         */
        MenuItem: {
            /**
             * Id
             * @description Stable item slug, e.g. matcha-sua.
             * @example matcha-sua
             */
            id: string;
            /**
             * Name
             * @description English name.
             * @example Matcha Latte
             */
            name: string;
            /**
             * Namevi
             * @description Vietnamese name as printed on the recipes menu.
             * @example Matcha Sữa
             */
            nameVi: string;
            /**
             * Description
             * @description English description from the recipes menu.
             * @example Koicha whisked thick, your sweetener and milk of choice.
             */
            description: string;
            /**
             * Categoryid
             * @description Owning category slug.
             * @example mat-cha
             */
            categoryId: string;
            /**
             * Temperatures
             * @description Offered service temperatures, at least one.
             * @example [
             *       "hot",
             *       "iced"
             *     ]
             */
            temperatures: components["schemas"]["Temperature"][];
            /**
             * Modifiergroupids
             * @description Customization groups allowed on this item, per cafe.md.
             * @example [
             *       "milk-matcha-latte",
             *       "sweetener-matcha",
             *       "sweetness",
             *       "cold-foam"
             *     ]
             */
            modifierGroupIds: string[];
            /**
             * Imagepath
             * @description Optional photo served at /images/menu/<itemId>.<ext>; absent means the on-brand placeholder.
             * @default null
             * @example /images/menu/matcha-sua.jpg
             */
            imagePath: string | null;
        };
        /**
         * ModifierDimension
         * @description Which frozen customization dimension a modifier group expresses.
         * @enum {string}
         */
        ModifierDimension: "milk" | "sweetener_type" | "sweetness_level" | "cold_foam";
        /**
         * ModifierGroup
         * @description A customization group allowed on one or more menu items.
         * @example {
         *       "defaultByTemperature": {
         *         "hot": "whole-milk",
         *         "iced": "oat-milk"
         *       },
         *       "dimension": "milk",
         *       "id": "milk-matcha-latte",
         *       "name": "Milk",
         *       "options": [
         *         {
         *           "id": "whole-milk",
         *           "name": "Whole milk",
         *           "temperatures": [
         *             "hot"
         *           ]
         *         },
         *         {
         *           "id": "oat-milk",
         *           "name": "Oat milk",
         *           "temperatures": [
         *             "hot",
         *             "iced"
         *           ]
         *         }
         *       ],
         *       "required": true
         *     }
         */
        ModifierGroup: {
            /**
             * Id
             * @description Stable group slug, e.g. milk-matcha-latte.
             * @example milk-matcha-latte
             */
            id: string;
            /** @description Which customization dimension this group expresses. */
            dimension: components["schemas"]["ModifierDimension"];
            /**
             * Name
             * @description Display name of the group.
             * @example Milk
             */
            name: string;
            /**
             * Required
             * @description True when the guest must make exactly one selection.
             * @example true
             */
            required: boolean;
            /**
             * Options
             * @description Selectable options, each scoped to temperatures.
             */
            options: components["schemas"]["ModifierOption"][];
            /**
             * Defaultoptionid
             * @description Default selection when options do not vary by temperature.
             * @default null
             * @example condensed-milk
             */
            defaultOptionId: string | null;
            /**
             * Defaultbytemperature
             * @description Default selection per temperature when options vary by temperature, e.g. Matcha Sữa hot defaults to whole milk.
             * @default null
             * @example {
             *       "hot": "whole-milk",
             *       "iced": "milk-plus-cream"
             *     }
             */
            defaultByTemperature: {
                [key: string]: string;
            } | null;
        };
        /**
         * ModifierOption
         * @description One selectable option within a modifier group.
         * @example {
         *       "id": "oat-milk",
         *       "name": "Oat milk",
         *       "temperatures": [
         *         "hot",
         *         "iced"
         *       ]
         *     }
         */
        ModifierOption: {
            /**
             * Id
             * @description Stable option slug, e.g. oat-milk.
             * @example oat-milk
             */
            id: string;
            /**
             * Name
             * @description Display name spelled out to guests and baristas.
             * @example Oat milk
             */
            name: string;
            /**
             * Temperatures
             * @description Service temperatures at which this option is offered.
             * @example [
             *       "hot",
             *       "iced"
             *     ]
             */
            temperatures: components["schemas"]["Temperature"][];
        };
        /**
         * Order
         * @description An order as served by every order endpoint and both event
         *     payloads. Status changes live here; the daily number is short
         *     and callable (FR-3).
         * @example {
         *       "createdAt": "2026-09-03T15:04:05Z",
         *       "customerName": "Lan",
         *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "items": [
         *         {
         *           "coldFoamId": "foam-salted",
         *           "coldFoamName": "Salted Cold Foam",
         *           "itemId": "matcha-sua",
         *           "itemName": "Matcha Latte",
         *           "itemNameVi": "Matcha Sữa",
         *           "milkOptionId": "oat-milk",
         *           "milkOptionName": "Oat milk",
         *           "notes": null,
         *           "quantity": 2,
         *           "sweetenerTypeId": "condensed-milk",
         *           "sweetenerTypeName": "Condensed milk",
         *           "sweetnessLevelId": "50",
         *           "sweetnessLevelName": "50%",
         *           "temperature": "iced"
         *         }
         *       ],
         *       "orderNumber": 7,
         *       "status": "placed",
         *       "updatedAt": "2026-09-03T15:04:05Z"
         *     }
         */
        Order: {
            /**
             * Id
             * Format: uuid
             * @description Order id, stable across its lifetime.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /**
             * Ordernumber
             * @description Daily order number, reset each day.
             * @example 7
             */
            orderNumber: number;
            /** @description Current lifecycle status. */
            status: components["schemas"]["OrderStatus"];
            /**
             * Customername
             * @description Guest-given name, if any.
             * @default null
             * @example Lan
             */
            customerName: string | null;
            /**
             * Items
             * @description Line snapshots with resolved names.
             */
            items: components["schemas"]["OrderLineView"][];
            /**
             * Createdat
             * Format: date-time
             * @description Placement time, ISO 8601 UTC.
             * @example 2026-09-03T15:04:05Z
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             * @description Last transition time, ISO 8601 UTC.
             * @example 2026-09-03T15:09:11Z
             */
            updatedAt: string;
        };
        /**
         * OrderCreate
         * @description Request body of POST /api/orders.
         * @example {
         *       "customerName": "Lan",
         *       "items": [
         *         {
         *           "coldFoamId": "foam-salted",
         *           "itemId": "matcha-sua",
         *           "milkOptionId": "oat-milk",
         *           "notes": "extra hot, please",
         *           "quantity": 2,
         *           "sweetenerTypeId": "condensed-milk",
         *           "sweetnessLevelId": "50",
         *           "temperature": "iced"
         *         }
         *       ]
         *     }
         */
        OrderCreate: {
            /**
             * Customername
             * @description Optional name shown to the barista on the queue card.
             * @default null
             * @example Lan
             */
            customerName: string | null;
            /**
             * Items
             * @description Order lines; at least one.
             */
            items: components["schemas"]["OrderLine"][];
        };
        /**
         * OrderLine
         * @description One drink line in a placed order: the full selection snapshot
         *     (FR-2). Validated against the live menu: the item must exist,
         *     the temperature must be offered, and every selection must belong
         *     to a group the item allows at that temperature.
         * @example {
         *       "coldFoamId": "foam-salted",
         *       "itemId": "matcha-sua",
         *       "milkOptionId": "oat-milk",
         *       "notes": "extra hot, please",
         *       "quantity": 2,
         *       "sweetenerTypeId": "condensed-milk",
         *       "sweetnessLevelId": "50",
         *       "temperature": "iced"
         *     }
         */
        OrderLine: {
            /**
             * Itemid
             * @description Menu item id.
             * @example matcha-sua
             */
            itemId: string;
            /** @description Chosen service temperature; must be offered by the item. */
            temperature: components["schemas"]["Temperature"];
            /**
             * Quantity
             * @description Units of this line, 1 to 10.
             * @example 2
             */
            quantity: number;
            /**
             * Milkoptionid
             * @description Chosen milk option; must belong to the item's milk group at the chosen temperature.
             * @default null
             * @example oat-milk
             */
            milkOptionId: string | null;
            /**
             * Sweetenertypeid
             * @description Chosen sweetener; must belong to the item's sweetener group.
             * @default null
             * @example condensed-milk
             */
            sweetenerTypeId: string | null;
            /**
             * Sweetnesslevelid
             * @description Chosen sweetness step; one of full, 75, 50, 25, none.
             * @default null
             * @example 50
             */
            sweetnessLevelId: string | null;
            /**
             * Coldfoamid
             * @description Chosen cold foam build; allowed only when temperature is iced.
             * @default null
             * @example foam-salted
             */
            coldFoamId: string | null;
            /**
             * Notes
             * @description Free text for the barista, at most 200 characters.
             * @default null
             * @example extra hot, please
             */
            notes: string | null;
        };
        /**
         * OrderLineView
         * @description An order line as served in responses, with every selection
         *     resolved to its display name so both surfaces can spell out
         *     modifiers without a menu lookup (FR-5).
         * @example {
         *       "coldFoamId": "foam-salted",
         *       "coldFoamName": "Salted Cold Foam",
         *       "itemId": "matcha-sua",
         *       "itemName": "Matcha Latte",
         *       "itemNameVi": "Matcha Sữa",
         *       "milkOptionId": "oat-milk",
         *       "milkOptionName": "Oat milk",
         *       "notes": null,
         *       "quantity": 2,
         *       "sweetenerTypeId": "condensed-milk",
         *       "sweetenerTypeName": "Condensed milk",
         *       "sweetnessLevelId": "50",
         *       "sweetnessLevelName": "50%",
         *       "temperature": "iced"
         *     }
         */
        OrderLineView: {
            /**
             * Itemid
             * @description Menu item id.
             * @example matcha-sua
             */
            itemId: string;
            /**
             * Itemname
             * @description English item name.
             * @example Matcha Latte
             */
            itemName: string;
            /**
             * Itemnamevi
             * @description Vietnamese item name.
             * @example Matcha Sữa
             */
            itemNameVi: string;
            /** @description Chosen service temperature. */
            temperature: components["schemas"]["Temperature"];
            /**
             * Quantity
             * @description Units of this line, 1 to 10.
             * @example 2
             */
            quantity: number;
            /**
             * Milkoptionid
             * @description Chosen milk option id.
             * @default null
             * @example oat-milk
             */
            milkOptionId: string | null;
            /**
             * Milkoptionname
             * @description Chosen milk, spelled out.
             * @default null
             * @example Oat milk
             */
            milkOptionName: string | null;
            /**
             * Sweetenertypeid
             * @description Chosen sweetener id.
             * @default null
             * @example condensed-milk
             */
            sweetenerTypeId: string | null;
            /**
             * Sweetenertypename
             * @description Chosen sweetener, spelled out.
             * @default null
             * @example Condensed milk
             */
            sweetenerTypeName: string | null;
            /**
             * Sweetnesslevelid
             * @description Chosen sweetness step id.
             * @default null
             * @example 50
             */
            sweetnessLevelId: string | null;
            /**
             * Sweetnesslevelname
             * @description Chosen sweetness, spelled out.
             * @default null
             * @example 50%
             */
            sweetnessLevelName: string | null;
            /**
             * Coldfoamid
             * @description Chosen cold foam id.
             * @default null
             * @example foam-salted
             */
            coldFoamId: string | null;
            /**
             * Coldfoamname
             * @description Chosen cold foam, spelled out.
             * @default null
             * @example Salted Cold Foam
             */
            coldFoamName: string | null;
            /**
             * Notes
             * @description Free text for the barista.
             * @default null
             * @example extra hot
             */
            notes: string | null;
        };
        /**
         * OrderRules
         * @description Frozen per-line bounds shared by both surfaces (PRD section 4).
         * @example {
         *       "maxQuantity": 10,
         *       "minQuantity": 1,
         *       "notesMaxLength": 200
         *     }
         */
        OrderRules: {
            /**
             * Notesmaxlength
             * @description Maximum characters of free text per order line.
             * @example 200
             */
            notesMaxLength: number;
            /**
             * Minquantity
             * @description Minimum units per order line.
             * @example 1
             */
            minQuantity: number;
            /**
             * Maxquantity
             * @description Maximum units per order line.
             * @example 10
             */
            maxQuantity: number;
        };
        /**
         * OrderStatus
         * @description Lifecycle states from FR-7. Legal transitions: placed to
         *     in_progress, in_progress to completed, placed to completed,
         *     placed to cancelled. Everything else is rejected.
         * @enum {string}
         */
        OrderStatus: "placed" | "in_progress" | "completed" | "cancelled";
        /**
         * OrderStatusUpdate
         * @description Request body of PATCH /api/orders/{id}/status. Rejected with
         *     422 when the transition is illegal (FR-7).
         * @example {
         *       "status": "in_progress"
         *     }
         */
        OrderStatusUpdate: {
            /**
             * @description Target status; must be reachable from the current one.
             * @example in_progress
             */
            status: components["schemas"]["OrderStatus"];
        };
        /**
         * Temperature
         * @description Service temperature of a drink, from the nong/da tags.
         * @enum {string}
         */
        Temperature: "hot" | "iced";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * HeartbeatEvent
         * @description SSE keepalive sent every 25 seconds so idle connections and
         *     proxies keep the stream open.
         * @example {
         *       "sentAt": "2026-09-03T15:04:30Z",
         *       "type": "heartbeat"
         *     }
         */
        HeartbeatEvent: {
            /**
             * Type
             * @description Event discriminator.
             * @example heartbeat
             * @constant
             */
            type: "heartbeat";
            /**
             * Sentat
             * Format: date-time
             * @description Heartbeat time, ISO 8601 UTC.
             * @example 2026-09-03T15:04:30Z
             */
            sentAt: string;
        };
        /**
         * OrderNewEvent
         * @description SSE payload broadcast when an order is placed; consumed by the
         *     barista surface.
         * @example {
         *       "order": {
         *         "createdAt": "2026-09-03T15:04:05Z",
         *         "customerName": "Lan",
         *         "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *         "items": [
         *           {
         *             "coldFoamId": "foam-salted",
         *             "coldFoamName": "Salted Cold Foam",
         *             "itemId": "matcha-sua",
         *             "itemName": "Matcha Latte",
         *             "itemNameVi": "Matcha Sữa",
         *             "milkOptionId": "oat-milk",
         *             "milkOptionName": "Oat milk",
         *             "notes": null,
         *             "quantity": 2,
         *             "sweetenerTypeId": "condensed-milk",
         *             "sweetenerTypeName": "Condensed milk",
         *             "sweetnessLevelId": "50",
         *             "sweetnessLevelName": "50%",
         *             "temperature": "iced"
         *           }
         *         ],
         *         "orderNumber": 7,
         *         "status": "placed",
         *         "updatedAt": "2026-09-03T15:04:05Z"
         *       },
         *       "type": "order:new"
         *     }
         */
        OrderNewEvent: {
            /**
             * Type
             * @description Event discriminator.
             * @example order:new
             * @constant
             */
            type: "order:new";
            /** @description The freshly placed order. */
            order: components["schemas"]["Order"];
        };
        /**
         * OrderStatusEvent
         * @description SSE payload broadcast on every status transition; consumed by
         *     both surfaces.
         * @example {
         *       "order": {
         *         "createdAt": "2026-09-03T15:04:05Z",
         *         "customerName": "Lan",
         *         "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *         "items": [
         *           {
         *             "coldFoamId": "foam-salted",
         *             "coldFoamName": "Salted Cold Foam",
         *             "itemId": "matcha-sua",
         *             "itemName": "Matcha Latte",
         *             "itemNameVi": "Matcha Sữa",
         *             "milkOptionId": "oat-milk",
         *             "milkOptionName": "Oat milk",
         *             "notes": null,
         *             "quantity": 2,
         *             "sweetenerTypeId": "condensed-milk",
         *             "sweetenerTypeName": "Condensed milk",
         *             "sweetnessLevelId": "50",
         *             "sweetnessLevelName": "50%",
         *             "temperature": "iced"
         *           }
         *         ],
         *         "orderNumber": 7,
         *         "status": "in_progress",
         *         "updatedAt": "2026-09-03T15:09:11Z"
         *       },
         *       "type": "order:status"
         *     }
         */
        OrderStatusEvent: {
            /**
             * Type
             * @description Event discriminator.
             * @example order:status
             * @constant
             */
            type: "order:status";
            /** @description The order in its new state. */
            order: components["schemas"]["Order"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_menu_api_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuDocument"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    place_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    read_order_api_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_orders__order_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
