"""Generate web/src/views/ordering/lib/menuData.ts from menu/menu.json.

Invoked as `make menudata` (uv run python menu/generate_menudata.py).
menu/menu.json is the schema-validated artifact written by
server/app/menu_generator.py; the web ordering view keeps a dev/test
fallback copy of the same document as a typed export. The generated
MenuDocument type makes imagePath, defaultOptionId, and
defaultByTemperature non-optional nullables that menu.json omits, so
they are written out as explicit nulls. The export's object literal is
strict JSON (double-quoted keys, no trailing commas) so
site/test_menu_staleness.py can parse it with stdlib json.loads, and
the emitted text is guarded by a round-trip reparse before it is
written.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MENU = REPO_ROOT / "menu" / "menu.json"
DEFAULT_OUTPUT = REPO_ROOT / "web" / "src" / "views" / "ordering" / "lib" / "menuData.ts"

REQUIRED_DOCUMENT_KEYS = ("modifierGroups", "items")

HEADER = """\
import type { MenuDocument } from "../../../api/client";

/*
 * Generated by menu/generate_menudata.py (make menudata) from
 * menu/menu.json; do not edit by hand. The object literal stays strict
 * JSON (double-quoted keys, no trailing commas) so
 * site/test_menu_staleness.py can parse it. Absent imagePath normalizes
 * to null, and modifier groups carry defaultOptionId and
 * defaultByTemperature as explicit nulls, so the literal satisfies the
 * generated MenuDocument type.
 */
export const menuDocument: MenuDocument = """


class MenuDataGenerationError(Exception):
    """Raised when menu.json cannot become a parseable menuData.ts literal."""


def normalize(document: dict) -> dict:
    """Fill the fields menu.json omits but the web MenuDocument type
    requires, in place, and return the document.

    imagePath on every item and defaultOptionId/defaultByTemperature on
    every modifier group become explicit nulls when absent; values that
    are already present are never touched.
    """
    for group in document["modifierGroups"]:
        group.setdefault("defaultOptionId", None)
        group.setdefault("defaultByTemperature", None)
    for item in document["items"]:
        item.setdefault("imagePath", None)
    return document


def render(document: dict) -> str:
    """Return the full menuData.ts text for a menu document.

    The document is normalized, serialized as a strict JSON literal, and
    reparsed with stdlib json.loads; a literal that does not round-trip
    to the normalized document is a bug, so generation fails instead of
    writing a file the staleness test could not parse.
    """
    missing = [key for key in REQUIRED_DOCUMENT_KEYS if key not in document]
    if missing:
        raise MenuDataGenerationError(
            f"the menu document is missing {', '.join(map(repr, missing))}"
        )
    normalized = normalize(document)
    literal = json.dumps(normalized, indent=2, ensure_ascii=False)
    reparsed = json.loads(literal)
    if reparsed != normalized:
        raise MenuDataGenerationError(
            "the emitted menuData literal failed its round-trip reparse: "
            "the output would not be readable by site/test_menu_staleness.py"
        )
    return HEADER + literal + ";\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the web menuData.ts fallback copy from menu/menu.json"
    )
    parser.add_argument("--menu", type=Path, default=DEFAULT_MENU, help="input menu.json path")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT, help="output menuData.ts path")
    args = parser.parse_args(argv)
    try:
        document = json.loads(args.menu.read_text(encoding="utf-8"))
    except OSError as exc:
        print(f"generate-menudata: error: cannot read {args.menu}: {exc}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"generate-menudata: error: {args.menu} is not valid JSON: {exc}", file=sys.stderr)
        return 1
    if not isinstance(document, dict):
        print(
            f"generate-menudata: error: {args.menu} must be a JSON object, "
            f"got {type(document).__name__}",
            file=sys.stderr,
        )
        return 1
    try:
        text = render(document)
    except MenuDataGenerationError as exc:
        print(f"generate-menudata: error: {exc}", file=sys.stderr)
        return 1
    try:
        args.out.write_text(text, encoding="utf-8")
    except OSError as exc:
        print(f"generate-menudata: error: cannot write {args.out}: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
